# Generated by Django 5.2.2 on 2025-06-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_series_type_bet_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
