# Generated by Django 5.2.2 on 2025-06-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_match_is_live'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='is_live',
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('live', 'Прямо зараз'), ('upcoming', 'Найближчий'), ('finished', 'Завершений')], default='upcoming', max_length=10),
        ),
    ]
