# Generated by Django 5.2.2 on 2025-06-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_remove_match_is_live_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='map',
            name='current_weapon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='rounds_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
