# Generated by Django 5.2.2 on 2025-06-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='rounds_detail',
        ),
        migrations.AlterField(
            model_name='map',
            name='team1_score',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='map',
            name='team2_score',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
