# Generated by Django 5.2.2 on 2025-06-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_remove_map_rounds_detail_alter_map_team1_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='map_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
