# Generated by Django 5.2.2 on 2025-06-09 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_map_map_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_maps', to='matches.team'),
        ),
        migrations.AlterField(
            model_name='round',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.team'),
        ),
    ]
