# Generated by Django 5.2.2 on 2025-06-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_map_winner_alter_round_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='betting_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_odds',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_odds',
            field=models.FloatField(default=1.0),
        ),
    ]
