# Generated by Django 5.2.2 on 2025-06-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_match_betting_open_match_team1_odds_match_team2_odds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team1_odds',
            field=models.FloatField(default=1.9),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2_odds',
            field=models.FloatField(default=1.9),
        ),
    ]
