# Generated by Django 5.2.2 on 2025-06-09 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_alter_match_team1_odds_alter_match_team2_odds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='is_won',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='odds_at_bet_time',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='bet',
            name='profit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
