# Generated by Django 5.2.2 on 2025-06-09 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0013_bet_is_won_bet_odds_at_bet_time_bet_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team_winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='matches.team'),
        ),
    ]
