# Generated by Django 5.2.2 on 2025-06-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0014_match_team_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bet',
            name='odds_at_bet_time',
            field=models.DecimalField(decimal_places=0, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bet',
            name='profit',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=10),
        ),
    ]
