# Generated by Django 5.2.2 on 2025-06-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0015_alter_bet_amount_alter_bet_odds_at_bet_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='amount',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
    ]
