# Generated by Django 5.2.2 on 2025-06-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0016_alter_bet_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='odds_at_bet_time',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=10),
        ),
    ]
