# Generated by Django 5.2.2 on 2025-06-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_withdrawalrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='processed',
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='card_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує'), ('approved', 'Підтверджено'), ('rejected', 'Відхилено')], default='pending', max_length=10),
        ),
    ]
