# Generated by Django 5.2.2 on 2025-06-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_transaction_withdrawalrequest_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='card_number',
            field=models.CharField(blank=True, default='00000000', max_length=30),
        ),
    ]
