# Generated by Django 5.2.2 on 2025-06-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_withdrawalrequest_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
